### ISSUE TITLE
Setup Debug

### ISSUE THREAD

**Issue by LabSen** [ChrisRBe/PP-P2P-Parser#235]
Hi

I install python3 inkl. pip3 on Ubuntu. I clone this git repro and run "pip3 install ruamel.yaml". This is my debug, what's wrong?:

`root@docker:/home/psenn/PP-P2P-Parser# python3 parse-account-statements.py  --type mintos --debug 20201022-account-statement.csv 
INFO:Config ini
Traceback (most recent call last):
  File "parse-account-statements.py", line 90, in <module>
    sys.exit(main(CMD_ARGS.infile, CMD_ARGS.type))
  File "parse-account-statements.py", line 61, in main
    statement_list = platform_parser.parse_account_statement()
  File "/home/psenn/PP-P2P-Parser/src/p2p_account_statement_parser.py", line 78, in parse_account_statement
    category = sttmnt.get_category()
  File "/home/psenn/PP-P2P-Parser/src/Statement.py", line 28, in get_category
    booking_type = self._statement[self._config.get_booking_type()]
KeyError: 'Details'`

**Comment by ChrisRBe** [comment]
W/o seeing the original input files, looks like it can't find the 'Details' column. Will have a look at the code later tonight to see if I find anything obvious.

**Comment by ChrisRBe** [comment]
Could you paste the first (head line) of your mintos account statement in here?

**Comment by ChrisRBe** [comment]
I updated the included config to the latest header version with #236

**Comment by LabSen** [comment]
Thank you. Works now. Two Inputs:

1. portfolio_performance__mintos.csv is the final file. It's a "_" too much.
2. Secondary Market Transaction and Service Fee's are ignored.

**Comment by ChrisRBe** [comment]
Hey, 

Glad that it's working now.

> Thank you. Works now. Two Inputs:
> 
> 1. portfolio_performance__mintos.csv is the final file. It's a "_" too much.
> 2. Secondary Market Transaction and Service Fee's are ignored.

Re. 1: The second underscore is intentional and supposed to be a separator of sorts between the default file name and the platform used.
Re. 2: Yes, I am aware in a way. I have to check my latest account statement to see if there are any secondary market transactions included or not. Haven't done much on the secondary market. If you have some entries for them, feel free to raise a PR to add them. You would also have to update the regex in the mintos.yml file as well as update the unit test.
