### ISSUE TITLE
Handling of 'Discount/premium for secondary market transaction' from Mintos

### ISSUE THREAD

**Issue by Michi-4G** [ChrisRBe/PP-P2P-Parser#43]
Hi Chris,

I just used your parser to import my account statement from my Mintos account which worked very smooth - thanks a lot for your work!

However, I noticed a small difference after the import into Portfolio Performance: With the mintos default config secondary market transactions seem to be getting ignored.
For my I use case I solved this by adjusting the interest regex to something like this:
`  interest: "(^Delayed interest.*)|(^Late payment.*)|(^Interest income.*)|(^Cashback.*)|(^Discount.*)"`

This worked for me pretty well, because I only had positive (i.e. discounts) in my secondary market transactions. To be honest I am not sure how Portfolio Performance would handle negative interest statements. Do you have any better idea how to handle such secondary market transactions?

If this helps here is a complete example from the mintos export file:
`408071234;2018-08-20 16:36:14;Discount/premium for secondary market transaction 409801234 Loan ID: 3993123-01;0.014028056;0.541010512;EUR`

**Comment by ChrisRBe** [comment]
Hi Michi,

First of all, thank you for using my little tool. I'm glad that it seems to be useful to you.

I myself am not using the secondary market and haven't seen these secondary market statements in my account statement. That's why the parser didn't pick up this statement for processing.

Regarding your last question: 
I'm honestly not sure if these "discount/premiums for secondary market transactions" really constitute interest per se. It might be easier to treat them as deposits and withdrawals. On the other hand, such a solution would remove these payments from the performance calculation... Plus ... handling might get a bit complex,
I haven't tried feeding negative interest statements to Portfolio Performance yet, but I would assume that it should be reflected correctly.

**Comment by ChrisRBe** [comment]
No problem :) Let me know what they propose and I will see how to implement it on my side :)
